import { useStore } from '@/store';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, FileText, BarChart2, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';

// Zero-dependency PDF generator using browser print engine
function downloadPDF(title: string, content: string) {
  // Convert plain text report to styled HTML
  const htmlContent = content
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '<br/>');

  const styledHtml = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=JetBrains+Mono:wght@400;600&display=swap');
        * { margin: 0; padding: 0; box-sizing: border-box; }
        @page { margin: 40px 50px; size: A4; }
        body {
          font-family: 'JetBrains Mono', monospace;
          font-size: 11px;
          line-height: 1.7;
          color: #1a1a2e;
          background: white;
          padding: 40px;
        }
        .header {
          text-align: center;
          padding: 24px 0 20px;
          border-bottom: 3px solid #6366f1;
          margin-bottom: 24px;
        }
        .header h1 {
          font-family: 'Inter', sans-serif;
          font-size: 22px;
          font-weight: 700;
          color: #6366f1;
          letter-spacing: -0.5px;
        }
        .header p {
          font-family: 'Inter', sans-serif;
          font-size: 11px;
          color: #666;
          margin-top: 4px;
        }
        .content {
          white-space: pre-wrap;
          word-wrap: break-word;
          font-size: 10.5px;
        }
        .footer {
          margin-top: 32px;
          padding-top: 16px;
          border-top: 2px solid #e5e7eb;
          text-align: center;
          font-family: 'Inter', sans-serif;
          font-size: 9px;
          color: #9ca3af;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>⚡ AscendOS</h1>
        <p>${title} • Generated ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
      </div>
      <div class="content">${htmlContent}</div>
      <div class="footer">Generated by AscendOS — Master your potential.</div>
    </body>
    </html>
  `;

  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = 'none';
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) return;
  doc.open();
  doc.write(styledHtml);
  doc.close();

  // Wait for fonts to load, then trigger print → Save as PDF
  setTimeout(() => {
    iframe.contentWindow?.print();
    setTimeout(() => document.body.removeChild(iframe), 1000);
  }, 500);
}

export default function Reports() {
  const { focusTimeTotal, tasks, streak, productivityScore, goals, mentorTasks, user } = useStore();
  const [generating, setGenerating] = useState(false);

  const completedTasks = tasks.filter(t => t.status === 'done').length;

  const handleDownload = () => {
    setGenerating(true);
    setTimeout(() => {
      const now = new Date();
      const weekStart = new Date(now);
      weekStart.setDate(now.getDate() - now.getDay() + 1);
      const weekEnd = new Date(weekStart);
      weekEnd.setDate(weekStart.getDate() + 6);
      const fmt = (d: Date) => d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

      const myMentorTasks = mentorTasks.filter(t => t.assignedTo === user?.email);
      const gradedTasks = myMentorTasks.filter(t => t.status === 'graded');
      const avgScore = gradedTasks.length > 0 ? (gradedTasks.reduce((s, t) => s + (t.marks || 0), 0) / gradedTasks.length).toFixed(1) : 'N/A';
      const totalFocusHrs = Math.floor(focusTimeTotal / 60);
      const totalFocusMin = focusTimeTotal % 60;

      const report = `
╔══════════════════════════════════════════════════════════════╗
║                    ASCEND OS — WEEKLY REPORT                ║
╚══════════════════════════════════════════════════════════════╝

  Student:        ${user?.name || 'Student User'}
  Email:          ${user?.email || '—'}
  Period:         ${fmt(weekStart)} — ${fmt(weekEnd)}
  Generated:      ${fmt(now)} at ${now.toLocaleTimeString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  📊 PERFORMANCE OVERVIEW
  ───────────────────────
  Productivity Score:     ${productivityScore} / 100
  Current Streak:         ${streak} days
  Total Focus Time:       ${totalFocusHrs}h ${totalFocusMin}m
  XP Earned:              ${useStore.getState().xp} XP

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✅ TASK SUMMARY
  ───────────────
  Total Tasks:            ${tasks.length}
  Completed:              ${completedTasks}
  Completion Rate:        ${tasks.length > 0 ? Math.round((completedTasks / tasks.length) * 100) : 0}%

  Tasks Breakdown:
${tasks.map(t => `    ${t.status === 'done' ? '✓' : '○'} ${t.title} (${t.subject}) — ${t.priority} priority`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  🎯 GOALS PROGRESS
  ──────────────────
${goals.map(g => {
  const pct = g.target > 0 ? Math.round((g.progress / g.target) * 100) : 0;
  const bar = '█'.repeat(Math.floor(pct / 5)) + '░'.repeat(20 - Math.floor(pct / 5));
  return `    ${g.name} [${g.category}]\n    [${bar}] ${g.progress}/${g.target} (${pct}%)`;
}).join('\n\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  📝 MENTOR WORKSPACE
  ────────────────────
  Assigned Tasks:         ${myMentorTasks.length}
  Completed:              ${myMentorTasks.filter(t => t.status === 'submitted' || t.status === 'graded').length}
  Graded:                 ${gradedTasks.length}
  Average Score:          ${avgScore}

  Assignment Details:
${myMentorTasks.map(t => `    ${t.status === 'graded' ? '★' : t.status === 'submitted' ? '↑' : '○'} ${t.title}
      Subject: ${t.subject} | Assigned by: ${t.assignedBy}
      Status: ${t.status} | Progress: ${t.progress}%${t.marks !== undefined ? ` | Score: ${t.marks}/${t.maxMarks}` : ''}`).join('\n\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Generated by AscendOS — Master your potential.
  © ${now.getFullYear()} AscendOS
`.trim();

      downloadPDF('Weekly Report', report);
      setGenerating(false);
    }, 1200);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8 animate-fade-in-up">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Reports</h1>
          <p className="text-muted-foreground">Generate and download progress reports.</p>
        </div>
        <Button onClick={handleDownload} disabled={generating} className="gap-2">
          {generating ? <div className="h-4 w-4 rounded-full border-2 border-primary-foreground border-r-transparent animate-spin" /> : <Download className="h-4 w-4" />}
          {generating ? "Generating PDF..." : "Export Weekly Report"}
        </Button>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <Card className="bg-primary/5 border-primary/20">
          <CardHeader>
            <CardTitle className="text-xl flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              Weekly Summary
            </CardTitle>
            <CardDescription>Oct 23 - Oct 29</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <div className="flex justify-between items-center text-sm">
                <span className="text-muted-foreground flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-500" /> Tasks Done</span>
                <span className="font-bold">{completedTasks}</span>
              </div>
              <div className="flex justify-between items-center text-sm">
                <span className="text-muted-foreground flex items-center gap-2"><BarChart2 className="h-4 w-4 text-blue-500" /> Focus Hours</span>
                <span className="font-bold">{Math.round(focusTimeTotal / 60)}h {focusTimeTotal % 60}m</span>
              </div>
              <div className="flex justify-between items-center text-sm">
                <span className="text-muted-foreground flex items-center gap-2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-amber-500"><path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"/></svg> Eval Score</span>
                <span className="font-bold">{productivityScore}/100</span>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-xl flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Monthly Review
            </CardTitle>
            <CardDescription>September</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
             <div className="text-sm text-muted-foreground">
               Your productivity was 15% higher this week compared to your average in September. Great job keeping the streak alive!
             </div>
             <Button variant="outline" className="w-full">View Details</Button>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle className="text-xl flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Custom Range
            </CardTitle>
            <CardDescription>Select dates</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
              <div className="text-sm text-muted-foreground">
                Generate a custom report for any date range, including specific subject breakdowns and AI feedback.
              </div>
              <Button variant="outline" className="w-full">Select Dates</Button>
          </CardContent>
        </Card>
      </div>
      
      <div className="pt-6 border-t">
         <h2 className="text-xl font-bold mb-4">Historical Exports</h2>
         <div className="border rounded-md divide-y bg-card text-sm">
            {[
              { title: 'Midterm Preparation Cycle', date: 'Oct 15, 2026', size: '2.4 MB', content: `ASCEND OS — MIDTERM PREPARATION CYCLE\nPeriod: Oct 1 — Oct 15, 2026\n\n📊 OVERVIEW\n  Focus Hours: 42h 30m\n  Tasks Completed: 28 / 35\n  Subjects Covered: Adv. Calculus, Quantum Physics, Neurobiology\n  Productivity Score: 87/100\n\n📝 KEY HIGHLIGHTS\n  • Completed all Calculus problem sets ahead of schedule\n  • Quantum Physics — 3 practice exams done (avg: 78%)\n  • Neurobiology — Lab reports submitted on time\n  • Maintained 12-day study streak\n\n🎯 AREAS FOR IMPROVEMENT\n  • Macroeconomics review sessions were skipped 4 times\n  • Evening focus sessions dropped by 20%\n\nGenerated by AscendOS` },
              { title: 'September Growth Report', date: 'Oct 1, 2026', size: '1.8 MB', content: `ASCEND OS — SEPTEMBER GROWTH REPORT\nPeriod: Sep 1 — Sep 30, 2026\n\n📊 MONTHLY SUMMARY\n  Total Focus Time: 68h 15m\n  Tasks Completed: 45\n  Goals Achieved: 3 / 5\n  XP Earned: 4,120\n\n📈 GROWTH METRICS\n  • Focus time increased 15% vs August\n  • Task completion rate: 82% (up from 74%)\n  • Longest streak: 9 days\n  • Most productive day: Thursday (avg 3.2h)\n\n🏆 ACHIEVEMENTS UNLOCKED\n  • Deep Work Master — 5 consecutive 2h+ sessions\n  • Consistency King — 7-day streak\n  • Early Bird — Started before 8 AM 12 times\n\nGenerated by AscendOS` },
              { title: 'Summer AI Analysis', date: 'Sep 1, 2026', size: '3.1 MB', content: `ASCEND OS — SUMMER AI ANALYSIS\nPeriod: Jun — Aug 2026\n\n🤖 AI-POWERED INSIGHTS\n  Total Study Hours: 186h\n  Subjects Analyzed: 6\n  Optimal Study Window: 10 AM — 1 PM\n  Learning Velocity: 1.3x avg student\n\n📊 SUBJECT BREAKDOWN\n  Adv. Calculus:     ████████████████░░░░ 82%\n  Quantum Physics:   ██████████████░░░░░░ 71%\n  Neurobiology:      █████████████████░░░ 88%\n  Macroeconomics:    ██████████░░░░░░░░░░ 52%\n\n💡 AI RECOMMENDATIONS\n  1. Increase Macroeconomics sessions by 40%\n  2. Schedule Calculus during morning peak hours\n  3. Use spaced repetition for Physics formulas\n  4. Take breaks every 90 min (currently averaging 120 min)\n\nGenerated by AscendOS` },
            ].map((report, i) => (
            <div key={i} className="p-4 flex justify-between items-center hover:bg-muted/50 transition-colors">
               <div className="flex items-center gap-3">
                  <FileText className="h-5 w-5 text-red-400" />
                  <div>
                    <div className="font-medium">{report.title}</div>
                    <div className="text-muted-foreground text-xs">PDF • {report.size} • {report.date}</div>
                  </div>
               </div>
               <Button variant="ghost" size="icon" onClick={() => {
                 downloadPDF(report.title, report.content);
               }}><Download className="h-4 w-4" /></Button>
            </div>
            ))}
         </div>
      </div>
    </div>
  );
}
